### ISSUE TITLE
can I repost your post:https://dirkjanm.io/relaying-kerberos-over-dns-with-krbrelayx-and-mitm6/ on my site?

### ISSUE THREAD

**Issue by wqreytuk** [fox-it/mitm6#25]

**Comment by dirkjanm** [comment]
Depends on how. If it's just a literal copy/paste I don't see a reason to do that (but you're technically allowed to). If it's a translation then sure. As mentioned in the blog all content is available under the [Creative Commons BY 4.0 License](http://creativecommons.org/licenses/by/4.0/), which allows you to re-use it as long as you credit and link to the original post.

**Comment by wqreytuk** [comment]
> Depends on how. If it's just a literal copy/paste I don't see a reason to do that (but you're technically allowed to). If it's a translation then sure. As mentioned in the blog all content is available under the [Creative Commons BY 4.0 License](http://creativecommons.org/licenses/by/4.0/), which allows you to re-use it as long as you credit and link to the original post.

yeah, translation to Chinese accompany with some of my own words maybe
