### ISSUE TITLE
full machine-in-the-middle attack

### ISSUE THREAD

**Issue by mrbluecoat** [fox-it/mitm6#29]
> mitm6 doesn't implement a full machine-in-the-middle attack currently, like we see in for example the SLAAC attack

Any plans to support a full attack in the future? SLAAC attack requires a lot of tools and has been unstable in my experience. Perhaps [NAT64+DNS64](https://blog.obtusenet.com/dns64-nat64-on-openbsd/)?

**Comment by dirkjanm** [comment]
hey, it was my consideration at the time to add more attack options, but I'd rather keep this tool "simple" and do it's one function right, so no I'm not planning to add the full attack in the future, sorry!
