### ISSUE TITLE
invalid syntax in krbrelayx.py

### ISSUE THREAD

**Issue by AymanRbati** [fox-it/mitm6#30]
in line 55 of krbrelayx/lib/clients/httprelayclient.py a ':' should be added
this solved the issue for me

![image](https://user-images.githubusercontent.com/21956791/177282342-98d3ef2c-e1c6-4ece-9ce2-f80f6c1e23e3.png)

**Comment by dirkjanm** [comment]
Wrong repository for the bug report, but I've fixed it in https://github.com/dirkjanm/krbrelayx/commit/9c52825cc5834c981fe73a494f1a53779dbf8a16
Good catch, thanks for letting me know!
