### ISSUE TITLE
socket.gaierror

### ISSUE THREAD

**Issue by scorpius** [fox-it/mitm6#6]
I installed on kali via **`pip install mitm6,`** but I always get this error:

```Warning: Not filtering on any domain, mitm6 will reply to all DNS queries.
Unless this is what you want, specify at least one domain with -d
Traceback (most recent call last):
  File "/usr/local/bin/mitm6", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mitm6/mitm6.py", line 362, in main
    dnssock = setupFakeDns()
  File "/usr/local/lib/python2.7/dist-packages/mitm6/mitm6.py", line 284, in setupFakeDns
    addrinfo = socket.getaddrinfo(fulladdr, 53, socket.AF_INET6, socket.SOCK_DGRAM)
socket.gaierror: [Errno -2] Name or service not known
```

Any suggestions?

**Comment by scorpius** [comment]
Update: If my IPv6 address starts with 2601, I get the error above. If it starts with fe80, there's no error.

**Comment by dirkjanm** [comment]
Correct, you need to already have a link-local IPv6 address on the interface you're running mitm6 on, otherwise it will error out.

**Comment by scorpius** [comment]
ifconfig wlan0 shows that I have fe80 and 2601.
ifconfig eth0, shows that I just have just one fe80.

But when I start mitm6 on wlan0 it shows 2601, and then the error.

I must be doing something wrong somewhere.

**Comment by scorpius** [comment]
I think it was just auto detecting the wrong address. I used the -6 option with my IPv6 link-local address and got no more errors.

**Comment by dirkjanm** [comment]
Improved this behaviour in the latest version
